version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: emotion
    versions:
    - ">= 11.a, < 12"
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
