# https://taskfile.dev

version: "3"

tasks:
  update-dependencies:
    cmds:
      - git pull
      - rm -rf node_modules pnpm-lock.yaml
      - ncu -u
      - pnpm install
      - pnpm test
      - pnpm build
      - 'git add "*" && git commit -m "chore: update dependencies"'
      - npx standard-version
      - git push --follow-tags origin main
